name: 'My Action'
description: Test my action

# Inputs
inputs:
  # input name
  message:
    description: The message to print
    required: true
    default: Hi

runs:

  # Composite permite agrupar pasos
  using: "composite"

  steps:
    - uses: actions/checkout@v2
    - name: print message from inputs
      run: echo "${{ inputs.message }}"
      shell: bash
