name: Test

on:
  - push
  - pull_request

jobs:
  hola_job:

  steps:
    - name: Print Hola
      run: |
        echo "Hola mundo"

    - name: use my action
      uses: ./.github/actions/my-action
