name: Test

on:
  - push
  - pull_request

jobs:
  hola_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hola
        run: |
          echo "Hola mundo"

      - name: Checkout
        uses: actions/checkout@v4.1.7
            
      - name: use my action
        uses: ./.github/actions/my-action
