name: Test

# Eventos
on:
  - push

jobs:
  # NOmbre del job
  hola_job:

    # Maquina done se ejecute el job
    runs-on: ubuntu-latest

    steps:
      - name: Hi Word
        run: echo "Hi work"

  exec_neofetch:
    runs-on: ubuntu-latest

    steps:
      - name: Install neofech
        run: |
          apt-get install neofetch cat
          ls

      - name: Exec neofetch
        run: neofetch
