name: Test

on:
  - push
  - pull_request

jobs:
  hola_job:
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
          ports:
            - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Print Hola
        run: |
          echo "Hola mundo"

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: use my action
        uses: ./.github/actions/my-action
        with:
          message: my-value

      - name: print repo name
        run: echo "repo $GITHUB_REPOSITORY"

    steps:
      - name: Print secret value
        run: echo "Secreat value ${{ secrets.MY }}"
