name: Test

# Eventos
on:
  - push
  - pull_request

jobs:
  # NOmbre del job
  hola_job:

    # Maquina donde se ejecute el job
    runs-on: ubuntu-latest

    steps:
      - name: Hi Word
        run: echo "Hi work"

  exec_neofetch:
    runs-on: ubuntu-latest

    steps:
      - name: Install neofech
        run: |
          sudo apt-get install neofetch

      - name: Exec neofetch
        run: neofetch

  exec_ls:
    runs-on: ubuntu-latest
    needs: exec_neofetch

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: ls
        run: |
          chmod +x ./ls.sh
          ./ls.sh


      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4

      - name: node version
        run: node -v

      - name: Hello word in JS
        run: node hello.js
