name: Test

# Eventos
on:
  - push
  - pull_request

jobs:
  # NOmbre del job
  hola_job:

    # Maquina donde se ejecute el job
    runs-on: ubuntu-latest

    steps:
      - name: Hi Word
        run: echo "Hi work"

  exec_neofetch:
    runs-on: ubuntu-latest

    steps:
      - name: Install neofech
        run: |
          sudo apt-get install neofetch

      - name: Exec neofetch
        run: neofetch

    steps:
      - name: exec ls command
        run: ls
